apiVersion: apps/v1
kind: Deployment
metadata:
   name: bb-web
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: bb-web
   template:
      metadata:
         labels:
            app: bb-web
      spec:
         containers:
            - name: bb-site
              image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/sampleapp:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: bb-entrypoint
   namespace: default
spec:
   type: LoadBalancer
   selector:
      app: bb-web
   ports:
      - protocol: TCP
        port: 80
        targetPort: 8080  # Match with your containerPort
