apiVersion: apps/v1
kind: Deployment
metadata:
   name: sb-demo
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         sb: flask
   template:
      metadata:
         labels:
            sb: flask
      spec:
         containers:
            - name: flask-site
              image: kubernetesgcr/${{ secrets.GCP_PROJECT_ID }}/sampleapp:latest
              imagePullPolicy: Always              
---
apiVersion: v1
kind: Service
metadata:
   name: sb-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      sb: flask
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30002
