apiVersion: apps/v1
kind: Deployment
metadata:
   name: bb-demo
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: bb-web
   template:
      metadata:
         labels:
            app: bb-web
      spec:
         containers:
            - name: bb-site
              image: docker.io/${{ secrets.DOCKER_USERNAME }}/sampleapp:${{ github.sha }}
              imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
   name: bb-entrypoint
   namespace: default
spec:
   type: LoadBalancer
   selector:
      app: bb-web
   ports:
      - protocol: TCP
        port: 80
        targetPort: 8080  # Assuming your container exposes port 8080

